import AppKit
import SwiftUI

// Generated by scripts/design-tokens.mjs from client/design/tokens.json.
// Do not edit; run `npm run design:tokens` after changing web/assets/style.css.
// Every colour follows the window's appearance: the dark block under
// dark Aqua, the light block otherwise.
enum Tokens {
    static let bg = dynamic(dark: (11, 20, 30, 1), light: (244, 246, 249, 1))
    static let text = dynamic(dark: (248, 250, 252, 1), light: (11, 20, 30, 1))
    static let textSoft = dynamic(dark: (203, 213, 225, 1), light: (51, 65, 85, 1))
    static let muted = dynamic(dark: (136, 150, 166, 1), light: (91, 103, 118, 1))
    static let progress = dynamic(dark: (56, 189, 248, 1), light: (3, 105, 161, 1))
    static let ok = dynamic(dark: (95, 212, 162, 1), light: (22, 101, 52, 1))
    static let danger = dynamic(dark: (240, 146, 141, 1), light: (185, 28, 28, 1))
    static let panel = dynamic(dark: (255, 255, 255, 0.025), light: (15, 23, 42, 0.03))
    static let panelHover = dynamic(dark: (255, 255, 255, 0.045), light: (15, 23, 42, 0.05))
    static let border = dynamic(dark: (255, 255, 255, 0.08), light: (15, 23, 42, 0.1))

    private static func dynamic(
        dark: (Int, Int, Int, Double), light: (Int, Int, Int, Double)
    ) -> Color {
        Color(nsColor: NSColor(name: nil) { appearance in
            let isDark = appearance.bestMatch(from: [.aqua, .darkAqua]) == .darkAqua
            let c = isDark ? dark : light
            return NSColor(
                srgbRed: Double(c.0) / 255, green: Double(c.1) / 255, blue: Double(c.2) / 255,
                alpha: c.3)
        })
    }
}
