#!/usr/bin/env node
// Generates the design tokens the apps and the web share from the :root and
// light blocks of web/assets/style.css: client/design/tokens.json, the Swift
// enum the macOS shell reads, and the XAML theme dictionary the Windows shell
// merges. Run from the repo root: node scripts/design-tokens.mjs
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { pathToFileURL } from "node:url";

/// The tokens the shells draw with, in the order they are emitted.
export const SHELL_TOKENS = [
  "bg",
  "text",
  "text-soft",
  "muted",
  "progress",
  "ok",
  "danger",
  "panel",
  "panel-hover",
  "border",
];

export function tokensFromCss(css) {
  function block(selector) {
    const start = css.indexOf(`${selector} {`);
    if (start < 0) throw new Error(`no ${selector} block in style.css`);
    const body = css.slice(start, css.indexOf("\n}", start));
    const tokens = {};
    for (const [, name, value] of body.matchAll(/^\s*--([a-z0-9-]+):\s*([^;]+);/gm)) {
      tokens[name] = value.trim();
    }
    return tokens;
  }
  const dark = block(":root");
  const light = { ...dark, ...block(':root[data-theme="light"]') };
  return {
    generated: "scripts/design-tokens.mjs from web/assets/style.css",
    fonts: {
      text: "Plus Jakarta Sans",
      mono: "JetBrains Mono",
      wordmark: "Libre Caslon Display",
    },
    dark,
    light,
  };
}

/// A CSS colour as [r, g, b, a] with the channels in 0..255 and alpha in 0..1.
export function parseColor(value) {
  const hex = value.match(/^#([0-9a-f]{6})$/i);
  if (hex) {
    const n = parseInt(hex[1], 16);
    return [(n >> 16) & 255, (n >> 8) & 255, n & 255, 1];
  }
  const rgba = value.match(/^rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*(?:,\s*([\d.]+)\s*)?\)$/);
  if (rgba) return [Number(rgba[1]), Number(rgba[2]), Number(rgba[3]), rgba[4] === undefined ? 1 : Number(rgba[4])];
  throw new Error(`unsupported colour ${value}`);
}

const camel = (name) => name.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
const pascal = (name) => name.replace(/(^|-)([a-z])/g, (_, __, c) => c.toUpperCase());

export function renderSwift(tokens) {
  const lines = [
    "import AppKit",
    "import SwiftUI",
    "",
    "// Generated by scripts/design-tokens.mjs from client/design/tokens.json.",
    "// Do not edit; run `npm run design:tokens` after changing web/assets/style.css.",
    "// Every colour follows the window's appearance: the dark block under",
    "// dark Aqua, the light block otherwise.",
    "enum Tokens {",
  ];
  for (const name of SHELL_TOKENS) {
    const d = parseColor(tokens.dark[name]);
    const l = parseColor(tokens.light[name]);
    lines.push(`    static let ${camel(name)} = dynamic(dark: (${d.join(", ")}), light: (${l.join(", ")}))`);
  }
  lines.push(
    "",
    "    private static func dynamic(",
    "        dark: (Int, Int, Int, Double), light: (Int, Int, Int, Double)",
    "    ) -> Color {",
    "        Color(nsColor: NSColor(name: nil) { appearance in",
    "            let isDark = appearance.bestMatch(from: [.aqua, .darkAqua]) == .darkAqua",
    "            let c = isDark ? dark : light",
    "            return NSColor(",
    "                srgbRed: Double(c.0) / 255, green: Double(c.1) / 255, blue: Double(c.2) / 255,",
    "                alpha: c.3)",
    "        })",
    "    }",
    "}",
    "",
  );
  return lines.join("\n");
}

function argb([r, g, b, a]) {
  const hex = (n) => n.toString(16).padStart(2, "0").toUpperCase();
  return `#${hex(Math.round(a * 255))}${hex(r)}${hex(g)}${hex(b)}`;
}

export function renderXaml(tokens) {
  const theme = (block) => {
    const out = [];
    for (const name of SHELL_TOKENS) {
      const key = `Vot${pascal(name)}`;
      out.push(`      <Color x:Key="${key}">${argb(parseColor(block[name]))}</Color>`);
    }
    for (const name of SHELL_TOKENS) {
      const key = `Vot${pascal(name)}`;
      out.push(`      <SolidColorBrush x:Key="${key}Brush" Color="{StaticResource ${key}}" />`);
    }
    return out.join("\n");
  };
  return [
    "<!-- Generated by scripts/design-tokens.mjs from client/design/tokens.json.",
    "     Do not edit; run `npm run design:tokens` after changing web/assets/style.css.",
    "     Merged by App.xaml; pages read the keys through ThemeResource so the",
    "     colours follow the system theme. -->",
    '<ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"',
    '    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">',
    "  <ResourceDictionary.ThemeDictionaries>",
    '    <ResourceDictionary x:Key="Default">',
    theme(tokens.dark),
    "    </ResourceDictionary>",
    '    <ResourceDictionary x:Key="Light">',
    theme(tokens.light),
    "    </ResourceDictionary>",
    "  </ResourceDictionary.ThemeDictionaries>",
    "</ResourceDictionary>",
    "",
  ].join("\n");
}

export const OUTPUTS = {
  json: "client/design/tokens.json",
  swift: "client/macos/Votport/Tokens.swift",
  xaml: "client/windows/Votport/Tokens.xaml",
};

export function render(css) {
  const tokens = tokensFromCss(css);
  return {
    json: `${JSON.stringify(tokens, null, 2)}\n`,
    swift: renderSwift(tokens),
    xaml: renderXaml(tokens),
    tokens,
  };
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const out = render(readFileSync("web/assets/style.css", "utf8"));
  mkdirSync("client/design", { recursive: true });
  for (const [kind, path] of Object.entries(OUTPUTS)) writeFileSync(path, out[kind]);
  console.log(
    `${OUTPUTS.json}: ${Object.keys(out.tokens.dark).length} dark, ${Object.keys(out.tokens.light).length} light tokens; ${OUTPUTS.swift} and ${OUTPUTS.xaml} written`,
  );
}
